version: 2.1
setup: false
orbs:
  aws-ecs: circleci/aws-ecs@3.2.0
  aws-ecr: circleci/aws-ecr@8.1.2
  node: circleci/node@5.0.2
  docker: circleci/docker@1.5.0

jobs:
  test:
     machine:
      image: default
     steps:
      - checkout
      - run:
          name: Install Dependencies
          command: npm install
    
workflows:
  test-build-deploy:
    jobs:
      - test:
          filters:
            branches:
              only: main
      - aws-ecr/build-and-push-image: # Use the pre-defined `build-and-push-image`
          dockerfile: Dockerfile
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-cli-version: latest
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          path: .
          profile-name: default
          repo: b2c-auth-ms-staging
          region: ${AWS_REGION}
          registry-id: AWS_ECR_REGISTRY_ID
          tag: '${CIRCLE_WORKFLOW_ID}'
          push-image: true
          platform: linux/amd64
          requires:
            - test
          filters:
            branches:
              only: main 
      - aws-ecs/deploy-service-update:
          cluster: 'api-staging'
          container-image-name-updates: 'container=auth-container,tag=${CIRCLE_WORKFLOW_ID}'
          family: 'b2c-auth-ms-staging'
          service-name: 'auth-api-staging'
          requires:
            - aws-ecr/build-and-push-image
          filters:
            branches:
              only: main
     
