version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:14
    steps:
      - checkout

      # Cache Node.js dependencies
      - restore_cache:
          keys:
            - v1-node-modules-{{ checksum "package-lock.json" }}
            - v1-node-modules-
      
      - run:
          name: Install Dependencies
          command: npm install
      
      # Save Node.js dependencies to the cache
      - save_cache:
          paths:
            - node_modules
          key: v1-node-modules-{{ checksum "package-lock.json" }}
      
      # Run tests (optional)
      - run:
          name: Run Tests
          command: npm test

      # Build Docker image
      - setup_remote_docker:
          version: edge

      - run:
          name: Build Docker Image
          command: |
            docker build -t $AWS_ECR_REPO_URL:latest .

      # Authenticate Docker with AWS ECR
      - run:
          name: Authenticate with AWS ECR
          command: |
            aws --version
            aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ECR_REPO_URL

      # Push Docker image to AWS ECR
      - run:
          name: Push Docker Image to ECR
          command: |
            docker push $AWS_ECR_REPO_URL:latest

  deploy:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout

      # Update ECS service to deploy the new image
      - run:
          name: Update ECS Service with new image
          command: |
            ecs-cli configure --cluster $AWS_ECS_CLUSTER_NAME --region $AWS_DEFAULT_REGION
            ecs-cli compose --file docker-compose.yml service up --cluster-config $AWS_ECS_CLUSTER_NAME --ecs-params ecs-params.yml

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
