version: 2.1
setup: false
orbs:
  aws-ecs: circleci/aws-ecs@3.2.0
  aws-ecr: circleci/aws-ecr@8.1.2
  node: circleci/node@6.1.0
  docker: circleci/docker@2.7.1
jobs:
  test:
    docker:
      - image: cimg/base:2024.10
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package-lock.json" }}
              - v1-dependencies-
      - run:
          name: Install Dependencies
          command: npm install
     
    
 
workflows:
  test-build-deploy:
    jobs:
      - test:
          filters:
            branches:
              only: main
      - aws-ecr/build-and-push-image: # Use the pre-defined `build-and-push-image`
          dockerfile: Dockerfile
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-cli-version: latest
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          path: .
          profile-name: default
          repo: wpadmin2
          region: ${AWS_REGION}
          registry-id: AWS_ECR_REGISTRY_ID
          tag: '${CIRCLE_WORKFLOW_ID}'
          push-image: true
          platform: linux/amd64
          requires:
            - test
          filters:
            branches:
              only: main
      - aws-ecs/deploy-service-update:
          cluster: 'mera-cluster'
          container-image-name-updates: 'container=todo,tag=${CIRCLE_WORKFLOW_ID}'
          family: 'wpadmin2'
          service-name: 'todosvc'
          requires:
            - aws-ecr/build-and-push-image
          filters:
            branches:
              only: main
     
